export const FETCH_CLIENTS_REQUEST_LOADING = "FETCH_CLIENTS_REQUEST_LOADING";
export const FETCH_CLIENTS_REQUEST_FAIL = "FETCH_CLIENTS_REQUEST_FAIL";
export const FETCH_CLIENTS_REQUEST_SUCCESS = "FETCH_CLIENTS_REQUEST_SUCCESS";

export const UPDATE_CURRENT_CLIENT_POSITION_REQUEST_LOADING =
  "UPDATE_CURRENT_CLIENT_POSITION_REQUEST_LOADING";
export const UPDATE_CURRENT_CLIENT_POSITION_REQUEST_FAIL =
  "UPDATE_CURRENT_CLIENT_POSITION_REQUEST_FAIL";
export const UPDATE_CURRENT_CLIENT_POSITION_REQUEST_SUCCESS =
  "UPDATE_CURRENT_CLIENT_POSITION_REQUEST_SUCCESS";

export const FETCH_CURRENT_CLIENT_LOADING = "FETCH_CURRENT_CLIENT_LOADING";
export const FETCH_CURRENT_CLIENT_FAIL = "FETCH_CURRENT_CLIENT_FAIL";
export const FETCH_CURRENT_CLIENT_SUCCESS = "FETCH_CURRENT_CLIENT_SUCCESS";

export const CONNECTED_NEW_CLIENT = "CONNECTED_NEW_CLIENT";
export const DISCONNECTED_CLIENT = "DISCONNECTED_CLIENT";

export const UPDATE_CLIENT_POSITION = "UPDATE_CLIENT_POSITION";

export const DRAG_START_CURRENT_CLIENT_POSITION = "DRAG_START_CURRENT_CLIENT_POSITION";
export const DRAG_END_CURRENT_CLIENT_POSITION = "DRAG_END_CURRENT_CLIENT_POSITION";
export const MOVE_CURRENT_CLIENT_POSITION = "MOVE_CURRENT_CLIENT_POSITION";
